import type {Metadata} from "next";

import "./globals.css";
import localFont from "next/font/local";
import {SessionProvider} from "next-auth/react";

import {cn} from "@/lib/utils";
import ToasterComponent from "@/components/layout/toaster-component";
import Header from "@/components/layout/header";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {auth} from "@/lib/auth";

const interVariable = localFont({
  variable: "--font-sans",
  src: "../fonts/InterVariable.woff2",
  weight: "100 900",
  display: "swap",
  preload: true,
});

const geistMonoVariable = localFont({
  variable: "--font-geist-mono",
  src: "../fonts/GeistMonoVF.woff2",
  weight: "100 900",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "snippets_lab",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  const session = await auth();

  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={cn(
          `font-sans ${interVariable.variable} ${geistMonoVariable.variable} antialiased`,
          "grid grid-rows-[var(--layout-header-height)_1fr]",
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            disableTransitionOnChange
            enableSystem
            attribute="class"
            defaultTheme="system"
          >
            <Header />
            {children}

            <ToasterComponent />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
