import type {Metadata} from "next";

import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "snippets_lab",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
