export enum Language {
  JAVASCRIPT = "javascript",
  TYPESCRIPT = "typescript",
  YAML = "yaml",
  PYTHON = "python",
  RUST = "rust",
  GO = "go",
  JAVA = "java",
  CSHARP = "c#",
  PHP = "php",
  ANGULAR = "angular",
  SQL = "sql",
  VUE = "vue",
  CSS = "css",
  HTML = "html",
  MARKDOWN = "markdown",
  JSON = "json",
  XML = "xml",
  CPP = "c++",
  SASS = "sass",
  SVELTE = "svelte",
}
